name: Build & Deploy to S3 + CloudFront

on:
  push:
    branches: [prod]
  pull_request_target:
    branches: [prod]
    types: [closed]

jobs:
  build-and-deploy:
    if: >
      (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/prod' && !contains(github.event.head_commit.message, 'Merge pull request'))
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build   # change if your output dir differs (e.g. dist)

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Sync files to S3
        run: |
          aws s3 sync dist/ s3://tms-vue-app --delete

          # aws s3 cp dist/index.html s3://tms-vue-app/index.html \
          #   --cache-control "no-cache, no-store, must-revalidate" \
          #   --content-type "text/html; charset=utf-8"

          # aws s3 cp --recursive --exclude "*" --include "*.js"  dist/ s3://tms-vue-app/ --cache-control "public, max-age=31536000, immutable"
          # aws s3 cp --recursive --exclude "*" --include "*.css" dist/ s3://tms-vue-app/ --cache-control "public, max-age=31536000, immutable"

      - name: Create CloudFront invalidation
        run: |
          # replace with your CloudFront distribution ID
          DISTRIBUTION_ID=EO44V0V4IOIB1
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
